### ISSUE TITLE
Action break with multiple paths

### ISSUE THREAD

**Issue by Crysicia** [alexandregv/norminette-action#1]
Hello,

The norminette v3 action doesn't handle multiples paths passed as parameters using "flags"
Example:
`flags: 'includes/ srcs/ *.c'`
(As well as)
`flags: includes/ srcs/ *.c`
Outputs:
`'includes/ srcs/ *.c' no such file or directory`

This syntax used to work on the norminette v2 action.
I haven't find a workaround for this yet, but it may be an issue directly related to the norminette v3 and not the action itself.

**Comment by alexandregv** [comment]
Hi,
Thanks for the report !
This should now be fixed. Please let me now if you still have problems.

**Comment by Crysicia** [comment]
Everything works just fine now.
Thanks a lot for the fix and have a great Sunday :)
