### ISSUE TITLE
Erreur de Norme inexistante

### ISSUE THREAD

**Issue by romann-broque** [alexandregv/norminette-action#4]
Bonjour,
En utilisant le Git action norminette, celle-ci m'indique des erreurs de norme qui me semblent non justifiees.
Est-ce normal ?

Exemple:
<img width="641" alt="Screenshot 2023-03-22 at 09 56 29" src="https://user-images.githubusercontent.com/58867296/226851795-52fca503-ad62-4edc-a219-ddd939d1a138.png">
<img width="978" alt="Screenshot 2023-03-22 at 09 56 41" src="https://user-images.githubusercontent.com/58867296/226851804-37cec8e2-5952-4a7b-bb7e-4b6f37be54d8.png">

**Comment by alexandregv** [comment]
Bonjour,

`norminette-action` utilise [ `norminette-docker`](https://github.com/alexandregv/norminette-docker) qui se contente d'installer la norminette en version latest, puis la lance sur ton projet, cf [ces lignes](https://github.com/alexandregv/norminette-action/blob/master/action.yml#L16-L19).
Donc à priori c'est un soucis avec ton setup ou bien le code de la norminette, ce qui ne concerne pas norminette-action ou norminette-docker

**Comment by romann-broque** [comment]
> Bonjour,
> 
> `norminette-action` utilise [ `norminette-docker`](https://github.com/alexandregv/norminette-docker) qui se contente d'installer la norminette en version latest, puis la lance sur ton projet, cf [ces lignes](https://github.com/alexandregv/norminette-action/blob/master/action.yml#L16-L19). Donc à priori c'est un soucis avec ton setup ou bien le code de la norminette, ce qui ne concerne pas norminette-action ou norminette-docker

Merci pour la réponse ! :)
Ce qui est étrange, c'est que la norminette que j'utilise (qui est à jour) ne m'indique aucune erreur…
Aurais-tu une autre piste ?
Encore merci !

**Comment by guillaume-salle** [comment]
Bonjour,
j'ai eu moi aussi ce problème d'erreurs de norme sur la github action norminette mais pas sur la norminette en local.
Je me dis que c'est sans doute la version de la norminette qui date un peu sur l'image docker ? Le dernier push était il y a 2 ans.

Pour l'instant j'ai mis l'installation de la norminette dans ma github action et je n'ai plus ce problème, mais c'est un peu dommage d'installer la norminette à chaque push. L'idéal serait que l'image docker se rebuild à chaque màj de la norminette !

**Comment by alexandregv** [comment]
Bonjour, je viens de mettre à jour le repo. Il y a désormais un tag pour chaque version de norminette, par example v3.3.51 ou v3.3.53  
Chaque campus peut utiliser une version différente, par exemple à 42Paris c'est encore la 3.3.51 qui est utilisée.
